/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patstake1;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerListModel;
import static patstake1.addLessonForm.ADDED_ARRAY;

/**
 *
 * @author YishaiBasserabie
 */
public class editLessonForm extends javax.swing.JFrame {

    //arrayList of students
    public static ArrayList<String> ADDED_ARRAY = new ArrayList<>();
    //list model
    DefaultListModel StudentsAddedListModel = new DefaultListModel();
    DefaultListModel checkListModel = new DefaultListModel();
    
    /**
     * Creates new form editLessonForm
     */
    public editLessonForm() {
        initComponents();
        //sets the visibility of all edit entties to false
        this.editDateTimePanel.setVisible(false);
        this.editLessonButton.setVisible(false);
        this.editStudentPanel.setVisible(false);
        this.editVenuePanel.setVisible(false);
        this.studentsAddedLabel.setVisible(false);
        
        this.studentsAddedList.removeAll(); //removes generic items from studentsAddedList
        this.addStudentNameComboBox.removeAllItems();//removes all generic tiems from name combo box
        populateComboBoxes pop = new populateComboBoxes();
        //populates grade combo box
        DefaultComboBoxModel grades = new DefaultComboBoxModel(pop.populateGrades());
        this.addStudentGradeComboBox.setModel(grades);
        //populates venues combo box
        DefaultComboBoxModel venues = new DefaultComboBoxModel(pop.populateVenues());
        this.addVenueComboBox.setModel(venues);
        //populates duration spinner with hour options
        SpinnerListModel hours = new SpinnerListModel(pop.populateDurationSpinner());
        this.durationSpinner.setModel(hours);
        //creates and populates a reference listModel
        CalendarHandler ch = new CalendarHandler();
        for (int i = 0; i < ch.studentsFromLessonDateAndTime(lesson.SELECTED_LESSON_DATE, lesson.SELECTED_LESSON_TIME).length; i++) {
            ADDED_ARRAY.add(ch.studentsFromLessonDateAndTime(lesson.SELECTED_LESSON_DATE, lesson.SELECTED_LESSON_TIME)[i]);
            this.StudentsAddedListModel.addElement(ADDED_ARRAY.get(i));
            checkListModel.addElement(ADDED_ARRAY.get(i));
            System.out.println(checkListModel.getElementAt(i));
        }
        this.studentsAddedList.setModel(checkListModel);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        addlessonLabel = new javax.swing.JLabel();
        backToDashboardButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentsAddedList1 = new javax.swing.JList<>();
        addLessonButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        addStudentGradeComboBox1 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        studentBeingAddedTextField1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        addStudentNameComboBox1 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        deleteStudentFromLessonButton1 = new javax.swing.JButton();
        addStudentToLessonButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        addDateComboBox1 = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        addLessonTimeHourComboBox1 = new javax.swing.JComboBox<>();
        addLessonTimeMinuteComboBox1 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        durationSpinner1 = new javax.swing.JSpinner();
        jLabel24 = new javax.swing.JLabel();
        timeSetLabel1 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        frequencyComboBox1 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        addVenueComboBox = new javax.swing.JComboBox<>();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        editVenuePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        venuesComboBox = new javax.swing.JComboBox<>();
        studentsAddedLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentsAddedList = new javax.swing.JList<>();
        editStudentPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        addStudentGradeComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        studentBeingAddedTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        addStudentNameComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        deleteStudentFromLessonButton = new javax.swing.JButton();
        addStudentToLessonButton = new javax.swing.JButton();
        editDateTimePanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        addDateComboBox = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        addLessonTimeHourComboBox = new javax.swing.JComboBox<>();
        addLessonTimeMinuteComboBox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        durationSpinner = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        timeSetLabel = new javax.swing.JLabel();
        editLessonButton = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        dateTimeCheck = new javax.swing.JCheckBox();
        studentsCheck = new javax.swing.JCheckBox();
        venueCheck = new javax.swing.JCheckBox();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addlessonLabel.setText("add lesson!");

        backToDashboardButton.setText("back");
        backToDashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToDashboardButtonActionPerformed(evt);
            }
        });

        jLabel15.setText("students added:");

        jScrollPane2.setViewportView(studentsAddedList1);

        addLessonButton.setText("add lesson!");
        addLessonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLessonButtonActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel16.setText("add student:");

        addStudentGradeComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "11", "12" }));
        addStudentGradeComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentGradeComboBox1ActionPerformed(evt);
            }
        });

        jLabel17.setText("grade:");

        studentBeingAddedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentBeingAddedTextField1ActionPerformed(evt);
            }
        });
        studentBeingAddedTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                studentBeingAddedTextField1KeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                studentBeingAddedTextField1KeyPressed(evt);
            }
        });

        jLabel18.setText("Choose From Combo Box:");

        addStudentNameComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel19.setText("Or Start Typing The Name:");

        deleteStudentFromLessonButton1.setText("delete student");
        deleteStudentFromLessonButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentFromLessonButton1ActionPerformed(evt);
            }
        });

        addStudentToLessonButton1.setText("add student");
        addStudentToLessonButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentToLessonButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(addStudentToLessonButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteStudentFromLessonButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(addStudentGradeComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(studentBeingAddedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addStudentNameComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStudentGradeComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addStudentNameComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentBeingAddedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteStudentFromLessonButton1)
                    .addComponent(addStudentToLessonButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel20.setText("Set Lesson Date, Time, And Frequency:");

        jLabel21.setText("Date:");

        jLabel22.setText("Time:");

        addLessonTimeHourComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        addLessonTimeHourComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLessonTimeHourComboBox1ActionPerformed(evt);
            }
        });

        addLessonTimeMinuteComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLessonTimeMinuteComboBox1ActionPerformed(evt);
            }
        });

        jLabel23.setText("Duration(hours):");

        durationSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                durationSpinner1StateChanged(evt);
            }
        });

        jLabel24.setText("Time Set:");

        timeSetLabel1.setText("------------------");

        jLabel25.setText("Frequency:");

        frequencyComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "once off", "weekly", "monthly" }));
        frequencyComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frequencyComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(addDateComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(addLessonTimeHourComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addLessonTimeMinuteComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(frequencyComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(durationSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeSetLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDateComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLessonTimeHourComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addLessonTimeMinuteComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(durationSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeSetLabel1)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(frequencyComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel26.setText("Set Venue:");

        addVenueComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addVenueComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVenueComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(addVenueComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addVenueComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(backToDashboardButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addlessonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addLessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(653, 653, 653))))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addlessonLabel)
                    .addComponent(backToDashboardButton))
                .addGap(24, 24, 24)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(14, 14, 14))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addLessonButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cancelButton.setText("cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Editing Lesson On:");

        jLabel2.setText("jLabel2");

        editVenuePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Venue:");

        venuesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout editVenuePanelLayout = new javax.swing.GroupLayout(editVenuePanel);
        editVenuePanel.setLayout(editVenuePanelLayout);
        editVenuePanelLayout.setHorizontalGroup(
            editVenuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editVenuePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editVenuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editVenuePanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(venuesComboBox, 0, 289, Short.MAX_VALUE))
                .addContainerGap())
        );
        editVenuePanelLayout.setVerticalGroup(
            editVenuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editVenuePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(venuesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        studentsAddedLabel.setText("students added:");

        jScrollPane1.setViewportView(studentsAddedList);

        editStudentPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("add student:");

        addStudentGradeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "11", "12" }));
        addStudentGradeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentGradeComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("grade:");

        studentBeingAddedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentBeingAddedTextFieldActionPerformed(evt);
            }
        });
        studentBeingAddedTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                studentBeingAddedTextFieldKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                studentBeingAddedTextFieldKeyPressed(evt);
            }
        });

        jLabel9.setText("Choose From Combo Box:");

        addStudentNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Or Start Typing The Name:");

        deleteStudentFromLessonButton.setText("delete student");
        deleteStudentFromLessonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentFromLessonButtonActionPerformed(evt);
            }
        });

        addStudentToLessonButton.setText("add student");
        addStudentToLessonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentToLessonButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editStudentPanelLayout = new javax.swing.GroupLayout(editStudentPanel);
        editStudentPanel.setLayout(editStudentPanelLayout);
        editStudentPanelLayout.setHorizontalGroup(
            editStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editStudentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(editStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(editStudentPanelLayout.createSequentialGroup()
                        .addComponent(addStudentToLessonButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteStudentFromLessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(editStudentPanelLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(addStudentGradeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(studentBeingAddedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addStudentNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        editStudentPanelLayout.setVerticalGroup(
            editStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStudentGradeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addStudentNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentBeingAddedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteStudentFromLessonButton)
                    .addComponent(addStudentToLessonButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editDateTimePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setText("Set Lesson Date, Time, And Frequency:");

        jLabel10.setText("Date:");

        jLabel11.setText("Time:");

        addLessonTimeHourComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        addLessonTimeHourComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLessonTimeHourComboBoxActionPerformed(evt);
            }
        });

        addLessonTimeMinuteComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLessonTimeMinuteComboBoxActionPerformed(evt);
            }
        });

        jLabel12.setText("Duration(hours):");

        durationSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                durationSpinnerStateChanged(evt);
            }
        });

        jLabel13.setText("Time Set:");

        timeSetLabel.setText("------------------");

        javax.swing.GroupLayout editDateTimePanelLayout = new javax.swing.GroupLayout(editDateTimePanel);
        editDateTimePanel.setLayout(editDateTimePanelLayout);
        editDateTimePanelLayout.setHorizontalGroup(
            editDateTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDateTimePanelLayout.createSequentialGroup()
                .addComponent(addDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(editDateTimePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editDateTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(editDateTimePanelLayout.createSequentialGroup()
                        .addComponent(addLessonTimeHourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addLessonTimeMinuteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editDateTimePanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(durationSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editDateTimePanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeSetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editDateTimePanelLayout.setVerticalGroup(
            editDateTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDateTimePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDateTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLessonTimeHourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addLessonTimeMinuteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDateTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(durationSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDateTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeSetLabel)
                    .addComponent(jLabel13))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        editLessonButton.setText("Update Lesson!");
        editLessonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editLessonButtonActionPerformed(evt);
            }
        });

        jLabel27.setText("NOTE: Please leave field blank if no edit is required");

        jLabel28.setText("What would you like to edit:");

        dateTimeCheck.setText("date/time");
        dateTimeCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTimeCheckActionPerformed(evt);
            }
        });

        studentsCheck.setText("students");
        studentsCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentsCheckActionPerformed(evt);
            }
        });

        venueCheck.setText("venue");
        venueCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venueCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(studentsAddedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addGap(18, 18, 18)
                                        .addComponent(dateTimeCheck)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(studentsCheck)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(venueCheck))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(editStudentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(editDateTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(editVenuePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(editLessonButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(dateTimeCheck)
                    .addComponent(studentsCheck)
                    .addComponent(venueCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(studentsAddedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editDateTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editStudentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editVenuePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editLessonButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStudentGradeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentGradeComboBoxActionPerformed
        ConnectDB db = new ConnectDB();
        studentsArray sa = new studentsArray();
        populateComboBoxes pop = new populateComboBoxes();
        //populates students combo box according to grade selected
        this.addStudentNameComboBox.removeAllItems();
        DefaultComboBoxModel correctedStudents = new DefaultComboBoxModel(pop.correctStudentsAccordingToGrade(this.addStudentGradeComboBox.getSelectedItem().toString()));
        this.addStudentNameComboBox.setModel(correctedStudents);
    }//GEN-LAST:event_addStudentGradeComboBoxActionPerformed

    private void studentBeingAddedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentBeingAddedTextFieldActionPerformed

    }//GEN-LAST:event_studentBeingAddedTextFieldActionPerformed

    private void studentBeingAddedTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentBeingAddedTextFieldKeyTyped

    }//GEN-LAST:event_studentBeingAddedTextFieldKeyTyped

    private void studentBeingAddedTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentBeingAddedTextFieldKeyPressed
        populateComboBoxes pop = new populateComboBoxes();
        if (!this.addStudentGradeComboBox.getSelectedItem().toString().equals("")) {
            DefaultComboBoxModel nameModel = new DefaultComboBoxModel(pop.correctStudentsAccordingToSearchTextField(this.addStudentGradeComboBox.getSelectedItem().toString(), this.studentBeingAddedTextField.getText()));
            this.addStudentNameComboBox.setModel(nameModel);
        } else {
            JOptionPane.showMessageDialog(null, "Before you start typing please select the grade :)");
        }
    }//GEN-LAST:event_studentBeingAddedTextFieldKeyPressed

    private void deleteStudentFromLessonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentFromLessonButtonActionPerformed
        lessonDataArray la = new lessonDataArray();
        
        String name = this.studentsAddedList.getSelectedValue();
        ADDED_ARRAY.remove(name);
        la.setNamesList(ADDED_ARRAY);
        this.StudentsAddedListModel.removeAllElements();
        for (int i = 0; i < la.getNames().size(); i++) {
            StudentsAddedListModel.addElement(la.getArrayOfStudentsAdded(i));
        }
        this.studentsAddedList.setModel(StudentsAddedListModel);
    }//GEN-LAST:event_deleteStudentFromLessonButtonActionPerformed

    private void addStudentToLessonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentToLessonButtonActionPerformed
        ConnectDB db = new ConnectDB();
        lessonDataArray la = new lessonDataArray();
        
        boolean alreadyIn  = false;
        String name = this.addStudentNameComboBox.getSelectedItem().toString();
        for (int i = 0; i < ADDED_ARRAY.size(); i++) {
            if (ADDED_ARRAY.get(i).equals(name)) {
                alreadyIn = true;
            }
        }
        if (alreadyIn == false) {
            ADDED_ARRAY.add(name);
        }
        la.setNamesList(ADDED_ARRAY);
        this.StudentsAddedListModel.removeAllElements();
        for (int i = 0; i < la.getNames().size(); i++) {
            StudentsAddedListModel.addElement(la.getArrayOfStudentsAdded(i));
        }
        this.studentsAddedList.setModel(StudentsAddedListModel);
    }//GEN-LAST:event_addStudentToLessonButtonActionPerformed

    private void addLessonTimeHourComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLessonTimeHourComboBoxActionPerformed
        populateComboBoxes pop = new populateComboBoxes();
        lessonDataArray la = new lessonDataArray();
        String timeSet = la.getLessonTimeFromStartTimeAndDuration(this.addLessonTimeHourComboBox.getSelectedItem().toString() + ":00", Integer.parseInt(this.durationSpinner.getModel().getValue().toString()));
        this.timeSetLabel.setText(timeSet);
        //populates minute combo box according to hour selected
        this.addLessonTimeMinuteComboBox.removeAllItems();//removes previously generated items in minute combo box
        DefaultComboBoxModel minutes = new DefaultComboBoxModel(pop.populateMinuteComboBoxAccordingToHour(this.addLessonTimeHourComboBox.getSelectedItem().toString()));
        this.addLessonTimeMinuteComboBox.setModel(minutes);
    }//GEN-LAST:event_addLessonTimeHourComboBoxActionPerformed

    private void addLessonTimeMinuteComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLessonTimeMinuteComboBoxActionPerformed
        lessonDataArray la = new lessonDataArray();
        String timeSet = la.getLessonTimeFromStartTimeAndDuration(this.addLessonTimeMinuteComboBox.getSelectedItem().toString(), Integer.parseInt(this.durationSpinner.getModel().getValue().toString()));
        this.timeSetLabel.setText(timeSet);
    }//GEN-LAST:event_addLessonTimeMinuteComboBoxActionPerformed

    private void durationSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_durationSpinnerStateChanged
        if (!this.addLessonTimeHourComboBox.getSelectedItem().toString().equals("")) {
            if (this.addLessonTimeMinuteComboBox.getSelectedItem().toString().equals("")) {
                lessonDataArray la = new lessonDataArray();
                String timeSet = la.getLessonTimeFromStartTimeAndDuration(this.addLessonTimeHourComboBox.getSelectedItem().toString() + ":00", Integer.parseInt(this.durationSpinner.getModel().getValue().toString()));
                this.timeSetLabel.setText(timeSet);
            } else {
                lessonDataArray la = new lessonDataArray();
                String timeSet = la.getLessonTimeFromStartTimeAndDuration(this.addLessonTimeMinuteComboBox.getSelectedItem().toString(), Integer.parseInt(this.durationSpinner.getModel().getValue().toString()));
                this.timeSetLabel.setText(timeSet);
            }
        } else {
            JOptionPane.showMessageDialog(null, "before choosing a duration please select a time");
        }
    }//GEN-LAST:event_durationSpinnerStateChanged

    private void backToDashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToDashboardButtonActionPerformed
        dashboard d = new dashboard();
        lessonDataArray la = new lessonDataArray();
        la.sortArray();
        d.setVisible(true);
        this.hide();
    }//GEN-LAST:event_backToDashboardButtonActionPerformed

    private void addLessonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLessonButtonActionPerformed
        
    }//GEN-LAST:event_addLessonButtonActionPerformed

    private void addStudentGradeComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentGradeComboBox1ActionPerformed
        ConnectDB db = new ConnectDB();
        studentsArray sa = new studentsArray();
        populateComboBoxes pop = new populateComboBoxes();
        //populates students combo box according to grade selected
        this.addStudentNameComboBox.removeAllItems();
        DefaultComboBoxModel correctedStudents = new DefaultComboBoxModel(pop.correctStudentsAccordingToGrade(this.addStudentGradeComboBox.getSelectedItem().toString()));
        this.addStudentNameComboBox.setModel(correctedStudents);
    }//GEN-LAST:event_addStudentGradeComboBox1ActionPerformed

    private void studentBeingAddedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentBeingAddedTextField1ActionPerformed

    }//GEN-LAST:event_studentBeingAddedTextField1ActionPerformed

    private void studentBeingAddedTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentBeingAddedTextField1KeyTyped

    }//GEN-LAST:event_studentBeingAddedTextField1KeyTyped

    private void studentBeingAddedTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentBeingAddedTextField1KeyPressed
        populateComboBoxes pop = new populateComboBoxes();
        if (!this.addStudentGradeComboBox.getSelectedItem().toString().equals("")) {
            DefaultComboBoxModel nameModel = new DefaultComboBoxModel(pop.correctStudentsAccordingToSearchTextField(this.addStudentGradeComboBox.getSelectedItem().toString(), this.studentBeingAddedTextField.getText()));
            this.addStudentNameComboBox.setModel(nameModel);
        } else {
            JOptionPane.showMessageDialog(null, "Before you start typing please select the grade :)");
        }
    }//GEN-LAST:event_studentBeingAddedTextField1KeyPressed

    private void deleteStudentFromLessonButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentFromLessonButton1ActionPerformed
        lessonDataArray la = new lessonDataArray();
        la.removeStudentAdded(this.studentsAddedList.getSelectedValue());
        System.out.println("selected: " + this.studentsAddedList.getSelectedValue());
        this.StudentsAddedListModel.removeAllElements();
        for (int i = 0; i < la.getNames().size(); i++) {
            StudentsAddedListModel.addElement(la.getArrayOfStudentsAdded(i));
        }
        this.studentsAddedList.setModel(StudentsAddedListModel);
    }//GEN-LAST:event_deleteStudentFromLessonButton1ActionPerformed

    private void addStudentToLessonButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentToLessonButton1ActionPerformed
        ConnectDB db = new ConnectDB();
        String name = this.addStudentNameComboBox.getSelectedItem().toString();
        lessonDataArray la = new lessonDataArray();
        la.addToNamesList(this.addStudentNameComboBox.getSelectedItem().toString());
        for (int i = 0; i < la.getNames().size(); i++) {
            StudentsAddedListModel.addElement(la.getArrayOfStudentsAdded(i));
        }
        this.studentsAddedList.setModel(StudentsAddedListModel);
    }//GEN-LAST:event_addStudentToLessonButton1ActionPerformed

    private void addLessonTimeHourComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLessonTimeHourComboBox1ActionPerformed
        populateComboBoxes pop = new populateComboBoxes();
        lessonDataArray la = new lessonDataArray();
        String timeSet = la.getLessonTimeFromStartTimeAndDuration(this.addLessonTimeHourComboBox.getSelectedItem().toString() + ":00", Integer.parseInt(this.durationSpinner.getModel().getValue().toString()));
        this.timeSetLabel.setText(timeSet);
        //populates minute combo box according to hour selected
        this.addLessonTimeMinuteComboBox.removeAllItems();//removes previously generated items in minute combo box
        DefaultComboBoxModel minutes = new DefaultComboBoxModel(pop.populateMinuteComboBoxAccordingToHour(this.addLessonTimeHourComboBox.getSelectedItem().toString()));
        this.addLessonTimeMinuteComboBox.setModel(minutes);
    }//GEN-LAST:event_addLessonTimeHourComboBox1ActionPerformed

    private void addLessonTimeMinuteComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLessonTimeMinuteComboBox1ActionPerformed
        lessonDataArray la = new lessonDataArray();
        String timeSet = la.getLessonTimeFromStartTimeAndDuration(this.addLessonTimeMinuteComboBox.getSelectedItem().toString(), Integer.parseInt(this.durationSpinner.getModel().getValue().toString()));
        this.timeSetLabel.setText(timeSet);
    }//GEN-LAST:event_addLessonTimeMinuteComboBox1ActionPerformed

    private void durationSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_durationSpinner1StateChanged
        if (!this.addLessonTimeHourComboBox.getSelectedItem().toString().equals("")) {
            if (this.addLessonTimeMinuteComboBox.getSelectedItem().toString().equals("")) {
                lessonDataArray la = new lessonDataArray();
                String timeSet = la.getLessonTimeFromStartTimeAndDuration(this.addLessonTimeHourComboBox.getSelectedItem().toString() + ":00", Integer.parseInt(this.durationSpinner.getModel().getValue().toString()));
                this.timeSetLabel.setText(timeSet);
            } else {
                lessonDataArray la = new lessonDataArray();
                String timeSet = la.getLessonTimeFromStartTimeAndDuration(this.addLessonTimeMinuteComboBox.getSelectedItem().toString(), Integer.parseInt(this.durationSpinner.getModel().getValue().toString()));
                this.timeSetLabel.setText(timeSet);
            }
        } else {
            JOptionPane.showMessageDialog(null, "before choosing a duration please select a time");
        }
    }//GEN-LAST:event_durationSpinner1StateChanged

    private void frequencyComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frequencyComboBox1ActionPerformed

    }//GEN-LAST:event_frequencyComboBox1ActionPerformed

    private void addVenueComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVenueComboBoxActionPerformed

    }//GEN-LAST:event_addVenueComboBoxActionPerformed

    private void dateTimeCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTimeCheckActionPerformed
        if (this.dateTimeCheck.isSelected()) {
            this.editDateTimePanel.setVisible(true);
            this.editLessonButton.setVisible(true);
        } else {
            if (this.editStudentPanel.isVisible() || this.editVenuePanel.isVisible()) {
                this.editDateTimePanel.setVisible(false);
            } else {
                this.editDateTimePanel.setVisible(false);
                this.editLessonButton.setVisible(false);
            }
        }
    }//GEN-LAST:event_dateTimeCheckActionPerformed

    private void studentsCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentsCheckActionPerformed
        if (this.studentsCheck.isSelected()) {
            this.editStudentPanel.setVisible(true);
            this.editLessonButton.setVisible(true);
        } else {
            if (this.editDateTimePanel.isVisible() || this.editVenuePanel.isVisible()) {
                this.editStudentPanel.setVisible(false);
            } else {
                this.editStudentPanel.setVisible(false);
                this.editLessonButton.setVisible(false);
            }
        }
    }//GEN-LAST:event_studentsCheckActionPerformed

    private void venueCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venueCheckActionPerformed
        if (this.venueCheck.isSelected()) {
            this.editVenuePanel.setVisible(true);
            this.editLessonButton.setVisible(true);
        } else {
            if (this.editDateTimePanel.isVisible() || this.editVenuePanel.isVisible()) {
                this.editVenuePanel.setVisible(false);
            } else {
                this.editVenuePanel.setVisible(false);
                this.editLessonButton.setVisible(false);
            }
        }
    }//GEN-LAST:event_venueCheckActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void editLessonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editLessonButtonActionPerformed
       lessonDataArray la = new lessonDataArray();
        boolean listEdited = false;
       if (!this.checkListModel.equals(this.StudentsAddedListModel)) {
           listEdited = true;
       }
       la.editLessonStudents(listEdited, ADDED_ARRAY, lesson.SELECTED_LESSON_ID, lesson.SELECTED_LESSON_DATE, lesson.SELECTED_LESSON_TIME);
    }//GEN-LAST:event_editLessonButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editLessonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editLessonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editLessonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editLessonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editLessonForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser addDateComboBox;
    private com.toedter.calendar.JDateChooser addDateComboBox1;
    private javax.swing.JButton addLessonButton;
    private javax.swing.JComboBox<String> addLessonTimeHourComboBox;
    private javax.swing.JComboBox<String> addLessonTimeHourComboBox1;
    private javax.swing.JComboBox<String> addLessonTimeMinuteComboBox;
    private javax.swing.JComboBox<String> addLessonTimeMinuteComboBox1;
    private javax.swing.JComboBox<String> addStudentGradeComboBox;
    private javax.swing.JComboBox<String> addStudentGradeComboBox1;
    private javax.swing.JComboBox<String> addStudentNameComboBox;
    private javax.swing.JComboBox<String> addStudentNameComboBox1;
    private javax.swing.JButton addStudentToLessonButton;
    private javax.swing.JButton addStudentToLessonButton1;
    private javax.swing.JComboBox<String> addVenueComboBox;
    private javax.swing.JLabel addlessonLabel;
    private javax.swing.JButton backToDashboardButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox dateTimeCheck;
    private javax.swing.JButton deleteStudentFromLessonButton;
    private javax.swing.JButton deleteStudentFromLessonButton1;
    private javax.swing.JSpinner durationSpinner;
    private javax.swing.JSpinner durationSpinner1;
    private javax.swing.JPanel editDateTimePanel;
    private javax.swing.JButton editLessonButton;
    private javax.swing.JPanel editStudentPanel;
    private javax.swing.JPanel editVenuePanel;
    private javax.swing.JComboBox<String> frequencyComboBox1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField studentBeingAddedTextField;
    private javax.swing.JTextField studentBeingAddedTextField1;
    private javax.swing.JLabel studentsAddedLabel;
    private javax.swing.JList<String> studentsAddedList;
    private javax.swing.JList<String> studentsAddedList1;
    private javax.swing.JCheckBox studentsCheck;
    private javax.swing.JLabel timeSetLabel;
    private javax.swing.JLabel timeSetLabel1;
    private javax.swing.JCheckBox venueCheck;
    private javax.swing.JComboBox<String> venuesComboBox;
    // End of variables declaration//GEN-END:variables
}
